### ISSUE TITLE
Link https://alexa.design/voice-robotics-workshop broken

### ISSUE THREAD

**Issue by guikcd** [alexa-labs/voice-robotics-workshop#1]
👋 
The link for the frontend files for this workshop is broken (actually, the voiceroboticsworkshop.com is still valid and has valid nameservers, but no records are found).

Do you have any information ?

**Comment by jbnunn** [comment]
Hi @guikcd -- thank you for pointing this out. We are moving the workshop so it's temporarily unavailable. i'll prioritize the move or bring the contents to this repo so it doesn't rely on an external source.

**Comment by rpcme** [comment]
Hello, when will the docs be available?

**Comment by jbnunn** [comment]
Thanks @guikcd and @rpcme -- the guide has now been moved into the repo.
